name: Build and Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Get username
        run: |
          echo $USER

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mouazmalik123/nodeimages1:latest .

      - name: Publish image to Docker Hub
        run: docker push mouazmalik123/nodeimages1:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            docker pull mouazmalik123/nodeimages1:latest
            if [ $(docker ps -q -f name=node-container1) ]; then
              docker rm -f node-container1
            fi
            docker run -d -p 3000:3000 --name node-container1 mouazmalik123/nodeimages1:latest
